In [ ]:
import torch
import numpy as np

* 텐서 초기화하기
1. 데이터로부터 직접 생성하기

In [ ]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [ ]:
print(data)
print(x_data)

[[1, 2], [3, 4]]
tensor([[1, 2],
        [3, 4]])


---
2. numpy 배열로부터 생성하기

In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(np_array)
print(x_np)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])


----
3. 다른 텐서로부터 생성하기 :  
명시적으로 재정의(override) 하지 않는다면, 인자로 주어진 텐서의 속성(shape, datatype)을 유지함

In [ ]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.4842, 0.3703],
        [0.0415, 0.3104]]) 



-------

### 텐서의 속성(Attribute)

In [ ]:
tensor = torch.rand(3,4,2)
print(f"Tensor: {tensor}\n")

print(f"Tensor shape: {tensor.shape}\n")
print(f"Tensor datatype: {tensor.dtype}\n")
print(f"Device tensor is stored on: {tensor.device}")

Tensor: tensor([[[0.8067, 0.0475],
         [0.0706, 0.2336],
         [0.7824, 0.0194],
         [0.0674, 0.9854]],

        [[0.5315, 0.5434],
         [0.0805, 0.6221],
         [0.7358, 0.4940],
         [0.4321, 0.5250]],

        [[0.4799, 0.5332],
         [0.3326, 0.2292],
         [0.2177, 0.3325],
         [0.8750, 0.6532]]])

Tensor shape: torch.Size([3, 4, 2])

Tensor datatype: torch.float32

Device tensor is stored on: cpu


----------

### 텐서 연산(Operation)


In [ ]:
#gpu가 존재하면 텐서를 이동
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on {tensor.device}")

Device tensor is stored on cuda:0


In [ ]:
tensor = torch.ones(4,4)
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
tensor[:,1] = 0
tensor[:,2] = 3
print(tensor)

tensor([[1., 0., 3., 1.],
        [1., 0., 3., 1.],
        [1., 0., 3., 1.],
        [1., 0., 3., 1.]])


* 텐서 합치기

In [ ]:
t1 = torch.cat([tensor,tensor,tensor], dim=1)
print(t1)

tensor([[1., 0., 3., 1., 1., 0., 3., 1., 1., 0., 3., 1.],
        [1., 0., 3., 1., 1., 0., 3., 1., 1., 0., 3., 1.],
        [1., 0., 3., 1., 1., 0., 3., 1., 1., 0., 3., 1.],
        [1., 0., 3., 1., 1., 0., 3., 1., 1., 0., 3., 1.]])


In [ ]:
t2 = torch.cat([tensor,tensor,tensor], dim=0)
print(t2)

tensor([[1., 0., 3., 1.],
        [1., 0., 3., 1.],
        [1., 0., 3., 1.],
        [1., 0., 3., 1.],
        [1., 0., 3., 1.],
        [1., 0., 3., 1.],
        [1., 0., 3., 1.],
        [1., 0., 3., 1.],
        [1., 0., 3., 1.],
        [1., 0., 3., 1.],
        [1., 0., 3., 1.],
        [1., 0., 3., 1.]])


* 텐서 곱하기 
 -  element-wise product 
 - matrix multiplication

In [ ]:
#element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
print(f"tensor*tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 0., 9., 1.],
        [1., 0., 9., 1.],
        [1., 0., 9., 1.],
        [1., 0., 9., 1.]]) 

tensor*tensor 
 tensor([[1., 0., 9., 1.],
        [1., 0., 9., 1.],
        [1., 0., 9., 1.],
        [1., 0., 9., 1.]])


In [ ]:
#matrix multiplication
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.]]) 

tensor @ tensor.T 
 tensor([[11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.]])


* 바꿔치기 연산(in-place)  
  접미사 _ 를 갖는 연산들은 바꿔치기(in-place)연산임  
  x.copy_() 나 x.t_() 는 x를 변경함 

* 메모리를 일부 절약하긴 하지만, 기록(history)이 즉시 삭제되어 도함수(derivative) 계산에 문제가 발생할 수 있으므로 권장하지 않음 !!!! 

In [ ]:
print(f"{tensor} \n")
tensor.add_(5)
print(f"tensor.add_한것 \n {tensor} ")

tensor([[16., 15., 18., 16.],
        [16., 15., 18., 16.],
        [16., 15., 18., 16.],
        [16., 15., 18., 16.]]) 

tensor.add_한것 
 tensor([[21., 20., 23., 21.],
        [21., 20., 23., 21.],
        [21., 20., 23., 21.],
        [21., 20., 23., 21.]]) 


----

### numpy 변환
cpu상의 텐서와 numpy배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됨!

In [ ]:
t = torch.ones(2,5)
print(t, "\n")
print(f"numpy: \n {t.numpy()} ")

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]) 

numpy: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 


In [ ]:
t.add_(1)
print(f"t: \n{t}\n")
print(f"n: \n{t.numpy()}")

t: 
tensor([[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]])

n: 
[[4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]]


### numpy배열을 텐서로 변환하기

In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)
print(n)
print(t)

np.add(n,1, out=n)
print(f"\nt:  {t}")
print(f"n:  {n}")

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

t:  tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n:  [2. 2. 2. 2. 2.]
